version: '3.1'

services:

  db:
    image: mysql:9.6
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy